"""PDF Report Generator."""

from datetime import datetime
from pathlib import Path
from langchain_core.tools import tool
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

from core.config import REPORTS_DIR


@tool
def generate_pdf_report(title: str, content: str, filename: str = None) -> dict:
    """
    Generate professional PDF report from markdown content.
    
    Args:
        title: Report title
        content: Markdown content
        filename: Output filename (auto if None)
    
    Returns:
        Dict with file_path and status
    """
    try:
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"research_report_{timestamp}.pdf"
        
        if not filename.endswith(".pdf"):
            filename += ".pdf"
        
        file_path = REPORTS_DIR / filename
        
        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            "CustomTitle", parent=styles["Title"],
            fontSize=24, textColor=HexColor("#1a1a2e"),
            spaceAfter=20, alignment=1,
        )
        
        h1_style = ParagraphStyle(
            "CustomH1", parent=styles["Heading1"],
            fontSize=18, textColor=HexColor("#16213e"),
            spaceBefore=15, spaceAfter=10,
        )
        
        h2_style = ParagraphStyle(
            "CustomH2", parent=styles["Heading2"],
            fontSize=14, textColor=HexColor("#16213e"),
            spaceBefore=12, spaceAfter=8,
        )
        
        body_style = ParagraphStyle(
            "CustomBody", parent=styles["BodyText"],
            fontSize=11, leading=16, spaceAfter=10,
        )
        
        story = []
        story.append(Paragraph(title, title_style))
        
        date_str = datetime.now().strftime("%B %d, %Y")
        story.append(Paragraph(
            f"<i>Generated on {date_str}</i>",
            ParagraphStyle("Date", parent=body_style, alignment=1)
        ))
        story.append(Spacer(1, 0.3 * inch))
        
        for line in content.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.1 * inch))
                continue
            
            if line.startswith("# "):
                story.append(Paragraph(line[2:], h1_style))
            elif line.startswith("## "):
                story.append(Paragraph(line[3:], h2_style))
            elif line.startswith("### "):
                story.append(Paragraph(line[4:], h2_style))
            elif line.startswith("- ") or line.startswith("* "):
                story.append(Paragraph(f"• {line[2:]}", body_style))
            else:
                line = line.replace("**", "<b>", 1).replace("**", "</b>", 1)
                line = line.replace("*", "<i>", 1).replace("*", "</i>", 1)
                story.append(Paragraph(line, body_style))
        
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            "Footer", parent=body_style,
            fontSize=9, alignment=1, textColor=HexColor("#666666"),
        )
        story.append(Paragraph(
            "Generated by AutoResearch Agent | Powered by Gemini & LangGraph",
            footer_style
        ))
        
        doc.build(story)
        
        return {
            "status": "success",
            "file_path": str(file_path),
            "filename": filename,
            "size_bytes": file_path.stat().st_size,
        }
    except Exception as e:
        return {"status": "error", "error": str(e)}
